name: Imaginary Number
favicon: null
layout_spectrum: 0.94073
typography_spectrum: 0.31362
title: Interactive Media Company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7d0b01'
    - '#ad2241'
    - '#d14864'
    - '#fe7357'
  brandStrength: 0.9454210905823857
  lightness: 0.969075373141095
  saturation: 0.6000249779317528
  rhythmicContrast: 0.6517658266238868
purpose: []
