name: Imaginary Number
favicon: null
layout_spectrum: 0.94073
typography_spectrum: 0.57178
title: 'Imaginary Number: Interactive Media Company'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#343434'
    - '#fefefe'
    - '#878787'
    - '#9d5b06'
  brandStrength: 0.5
  lightness: 0.969075373141095
  saturation: 0.6000249779317528
  rhythmicContrast: 0.6517658266238868
purpose: []
